services:
  hackernewsapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: hackernewsapp
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: "always"
    environment:
      - PORT=8080
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/hackernews?sslmode=disable
    volumes:
      - ./:/app/
  database:
    image: postgres
    container_name: hackernewsdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=hackernews
    volumes:
      - type: volume
        source: hackernewsdbdata
        target: /var/lib/postgresql/data

volumes:
  hackernewsdbdata: